### ISSUE TITLE
Getting a _.findWhere is not a function when using branch with wildcards

### ISSUE THREAD

**Issue by Norbz** [Strider-CD/strider-ssh-deploy#46]
Everytime I get a hook on a branch that should match a configuration with a wildcard (ex : release/*) strider crashes then restart.

It seems that the error comes from this plugin, since I get the following error :

```
Fri, 25 May 2018 16:53:21 GMT strider-runner-core:job TypeError: _.findWhere is not a function
0|strider  |     at discreteBranchFn (/home/strider/strider/node_modules/strider-ssh-deploy/lib/keys.js:42:30)
0|strider  |     at findBranch (/home/strider/strider/node_modules/strider-ssh-deploy/lib/keys.js:46:4)
0|strider  |     at Object.setContext (/home/strider/strider/node_modules/strider-ssh-deploy/lib/keys.js:8:19)
0|strider  |     at Object.deploy (/home/strider/strider/node_modules/strider-ssh-deploy/lib/deploy.js:52:12)
0|strider  |     at Object.runPlugin (/home/strider/strider/node_modules/strider-runner-core/lib/utils.js:27:25)
0|strider  |     at /home/strider/strider/node_modules/strider-runner-core/lib/job.js:366:15
0|strider  |     at /home/strider/strider/node_modules/strider-runner-core/node_modules/async/lib/async.js:551:21
0|strider  |     at /home/strider/strider/node_modules/strider-runner-core/node_modules/async/lib/async.js:227:13
0|strider  |     at iterate (/home/strider/strider/node_modules/strider-runner-core/node_modules/async/lib/async.js:134:13)
0|strider  |     at /home/strider/strider/node_modules/strider-runner-core/node_modules/async/lib/async.js:145:25
0|strider  |     at /home/strider/strider/node_modules/strider-runner-core/node_modules/async/lib/async.js:229:17
0|strider  |     at /home/strider/strider/node_modules/strider-runner-core/node_modules/async/lib/async.js:556:34
0|strider  |     at /home/strider/strider/node_modules/strider-runner-core/lib/utils.js:33:5
0|strider  |     at ChildProcess.<anonymous> (/home/strider/strider/node_modules/strider-runner-core/lib/job.js:252:9)
0|strider  |     at ChildProcess.emit (events.js:180:13)
0|strider  |     at ChildProcess.emit (domain.js:439:23)
0|strider  |     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
```

There isn't any findWhere function in lodash anymore.

an you please update to the proper lodash function signature ?

Thanks

**Comment by knownasilya** [comment]
Try updating to v1.0.2 in the plugins page
